#pragma once

#include "orc_abi.h"

#include <iostream>

namespace orc_sdk {

enum class Error : OrcError
{
  NONE                       = ORC_ERROR_NONE,
  ABI_VERSION_MISMATCH       = ORC_ERROR_ABI_VERSION_MISMATCH,
  INVALID_HANDLE             = ORC_ERROR_INVALID_HANDLE,
  INVALID_DIMENSIONS         = ORC_ERROR_INVALID_DIMENSIONS,
  TYPE_MISMATCH              = ORC_ERROR_TYPE_MISMATCH,
  INVALID_COMBINATIONS       = ORC_ERROR_INVALID_COMBINATIONS,
  PLUGIN_ALREADY_INITIALIZED = ORC_ERROR_PLUGIN_ALREADY_INITIALIZED,
  CONCURRENCY_PROBLEM        = ORC_ERROR_CONCURRENCY_PROBLEM,
  INVALID_PROXY              = ORC_ERROR_INVALID_PROXY,
  CANNOT_LOAD_PLUGINS        = ORC_ERROR_CANNOT_LOAD_PLUGINS,
  OUT_OF_BOUNDS              = ORC_ERROR_OUT_OF_BOUNDS,
  ALLOC_FAILED               = ORC_ERROR_ALLOC_FAILED,
  NULL_PTR                   = ORC_ERROR_NULL_PTR,
  MISSING_CAPABILITY         = ORC_ERROR_MISSING_CAPABILITY,
  INVALID_FUNCTION           = ORC_ERROR_INVALID_FUNCTION,
  INVALID_ARGUMENTS          = ORC_ERROR_INVALID_ARGUMENTS,
  SERIALIZATION_ERROR        = ORC_ERROR_SERIALIZATION_ERROR,
  INVALID_CONTEXT            = ORC_ERROR_INVALID_CONTEXT,
  DECK_DEPTH_OVERFLOW        = ORC_ERROR_DECK_DEPTH_OVERFLOW,
  UNKNOWN                    = ORC_ERROR_UNKNOWN,
};

std::ostream &operator<<(std::ostream &os, Error const e);

}  // namespace orc_sdk
