/* automatically generated by rust-bindgen 0.72.1 */

pub const ORC_TYPE_U8: u64 = 1;
pub const ORC_TYPE_U16: u64 = 2;
pub const ORC_TYPE_U32: u64 = 3;
pub const ORC_TYPE_U64: u64 = 4;
pub const ORC_TYPE_F32: u64 = 17;
pub const ORC_TYPE_F64: u64 = 18;
pub const ORC_TYPE_I8: u64 = 33;
pub const ORC_TYPE_I16: u64 = 34;
pub const ORC_TYPE_I32: u64 = 35;
pub const ORC_TYPE_I64: u64 = 36;
pub const ORC_TYPE_PROXY: u64 = 48;
pub const ORC_MSG_LEVEL_DEBUG: u8 = 1;
pub const ORC_MSG_LEVEL_INFO: u8 = 2;
pub const ORC_MSG_LEVEL_WARN: u8 = 3;
pub const ORC_MSG_LEVEL_ERROR: u8 = 4;
pub const ORC_MSG_LEVEL_FATAL: u8 = 5;
pub const ORC_ARGS_VARIADIC: u64 = 18446744073709551615;
pub const ORC_TYPE_ANY: u64 = 18446744073709551615;
pub const ORC_DIM_LENGTH: u32 = 0;
pub const ORC_DIM_MASS: u32 = 1;
pub const ORC_DIM_TIME: u32 = 2;
pub const ORC_DIM_ELECTRIC_CURRENT: u32 = 3;
pub const ORC_DIM_TEMPERATURE: u32 = 4;
pub const ORC_DIM_SUBSTANCE: u32 = 5;
pub const ORC_DIM_LUMINOSITY: u32 = 6;
pub const ORC_NUM_DIMS: u32 = 7;
pub const ORC_ERROR_NONE: u32 = 0;
pub const ORC_ERROR_ABI_VERSION_MISMATCH: u32 = 65281;
pub const ORC_ERROR_INVALID_HANDLE: u32 = 65282;
pub const ORC_ERROR_INVALID_DIMENSIONS: u32 = 65283;
pub const ORC_ERROR_TYPE_MISMATCH: u32 = 65284;
pub const ORC_ERROR_INVALID_COMBINATIONS: u32 = 65285;
pub const ORC_ERROR_PLUGIN_ALREADY_INITIALIZED: u32 = 65286;
pub const ORC_ERROR_CONCURRENCY_PROBLEM: u32 = 65287;
pub const ORC_ERROR_INVALID_PROXY: u32 = 65288;
pub const ORC_ERROR_CANNOT_LOAD_PLUGINS: u32 = 65289;
pub const ORC_ERROR_OUT_OF_BOUNDS: u32 = 65290;
pub const ORC_ERROR_ALLOC_FAILED: u32 = 65291;
pub const ORC_ERROR_NULL_PTR: u32 = 65292;
pub const ORC_ERROR_MISSING_CAPABILITY: u32 = 65293;
pub const ORC_ERROR_INVALID_FUNCTION: u32 = 65294;
pub const ORC_ERROR_UNKNOWN: u32 = 65535;
pub const ORC_DECK_PROXY_COPY_ALL: u8 = 1;
pub const ORC_DECK_PROXY_COPY_ITEMS: u8 = 2;
pub const ORC_DECK_PROXY_SHUFFLE: u8 = 3;
pub const ORC_ABI_VERSION: u64 = 1;
pub type OrcTypeId = u64;
pub type OrcMessageLevel = u8;
pub type OrcError = u32;
pub type OrcProxyType = u8;
#[doc = "This is just a tag used to identify the types of inputs and outputs of plugin functions.\n`OrcTypeId`, is the actual tag used by the host and plugin to distinguish the types.\n`name` and `desc` are just optional information to help the host / user understand what\nthe type is."]
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct OrcTypeInfo {
    pub type_id: OrcTypeId,
    pub name: *const ::std::os::raw::c_char,
    pub desc: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of OrcTypeInfo"][::std::mem::size_of::<OrcTypeInfo>() - 24usize];
    ["Alignment of OrcTypeInfo"][::std::mem::align_of::<OrcTypeInfo>() - 8usize];
    ["Offset of field: OrcTypeInfo::type_id"]
        [::std::mem::offset_of!(OrcTypeInfo, type_id) - 0usize];
    ["Offset of field: OrcTypeInfo::name"][::std::mem::offset_of!(OrcTypeInfo, name) - 8usize];
    ["Offset of field: OrcTypeInfo::desc"][::std::mem::offset_of!(OrcTypeInfo, desc) - 16usize];
};
impl Default for OrcTypeInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type OrcPluginFunction = ::std::option::Option<
    unsafe extern "C" fn(
        ctx: u64,
        inputs: *const OrcHandle,
        n_inputs: u64,
        outputs: *mut OrcHandle,
        n_outputs: u64,
    ) -> OrcError,
>;
#[doc = "Metadata for a function exposed by the plugin. All plugin functions have the same\nsignature. The metadata encodes information about the inputs, outputs, and the function\npointer.\n\n`name` and `desc` are optional strings that are meant to help the host / user understand\nwhat the function does. `n_inputs` and `n_outputs` can be any value, except\n`ORC_ARGS_VARIADIC`. If they are set to `ORC_ARGS_VARIADIC`, host will infer that the\nfunctions will support any number of inputs / outputs.\n\nIf `n_inputs` / `n_outputs` are set to a value other than `ORC_ARGS_VARIADIC`, then the\nhost can read the corresponding `input_types` and `output_types` arrays to infer the types\nexpected by the function. This should only be set if the function expects one concrete\ntype. If the function is generic / and can process many types, the corresponding type must\nbe set to `ORC_TYPE_ANY`. If the `input_types` and `output_types` pointers are set to\n`NULL`, the host must infer that all inputs and outputs can be of any type.\n\nThis metadata is a hint for the host. The plugin function must still validate all it's\ninputs, and outputs, counts, and types, and return appropriate errors. Conversely, even if\nthe metadata implies a certain input/output configuration is supported by the function,\nthe function may still fail when called with said inputs/outputs."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OrcFuncInfo {
    pub name: *const ::std::os::raw::c_char,
    pub desc: *const ::std::os::raw::c_char,
    pub n_inputs: u64,
    pub n_outputs: u64,
    pub input_types: *mut OrcTypeId,
    pub output_types: *mut OrcTypeId,
    pub func: OrcPluginFunction,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of OrcFuncInfo"][::std::mem::size_of::<OrcFuncInfo>() - 56usize];
    ["Alignment of OrcFuncInfo"][::std::mem::align_of::<OrcFuncInfo>() - 8usize];
    ["Offset of field: OrcFuncInfo::name"][::std::mem::offset_of!(OrcFuncInfo, name) - 0usize];
    ["Offset of field: OrcFuncInfo::desc"][::std::mem::offset_of!(OrcFuncInfo, desc) - 8usize];
    ["Offset of field: OrcFuncInfo::n_inputs"]
        [::std::mem::offset_of!(OrcFuncInfo, n_inputs) - 16usize];
    ["Offset of field: OrcFuncInfo::n_outputs"]
        [::std::mem::offset_of!(OrcFuncInfo, n_outputs) - 24usize];
    ["Offset of field: OrcFuncInfo::input_types"]
        [::std::mem::offset_of!(OrcFuncInfo, input_types) - 32usize];
    ["Offset of field: OrcFuncInfo::output_types"]
        [::std::mem::offset_of!(OrcFuncInfo, output_types) - 40usize];
    ["Offset of field: OrcFuncInfo::func"][::std::mem::offset_of!(OrcFuncInfo, func) - 48usize];
};
impl Default for OrcFuncInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = "This struct is how the plugin communicates to the host about itself.\n\n- abi_version: Must be populated with the that of the header that was used to compile the\nplugin.\n- name and desc: Optional information to help the host / user understand what the plugin\nis about.\n- types and n_types: Array of custom types that used by the functions of this plugin. It\ncan be `NULL` if `n_types` is zero. The plugin must not redeclare any of the primitive\ntypes, nor can its types conflict with the types of other types loaded by other plugins.\nThe plugin is advised to choose a randmly generated 64 bit string as it's `OrcTypeId`, so\nthat it doesn't conflict with any other plugin's types.\n- functions and n_functions: Array of functions exposed by this plugin. The pointer can be\n`NULL` if n_types is zero."]
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct OrcPlugin {
    pub abi_version: u64,
    pub name: *const ::std::os::raw::c_char,
    pub desc: *const ::std::os::raw::c_char,
    pub types: *const OrcTypeInfo,
    pub n_types: u64,
    pub functions: *const OrcFuncInfo,
    pub n_functions: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of OrcPlugin"][::std::mem::size_of::<OrcPlugin>() - 56usize];
    ["Alignment of OrcPlugin"][::std::mem::align_of::<OrcPlugin>() - 8usize];
    ["Offset of field: OrcPlugin::abi_version"]
        [::std::mem::offset_of!(OrcPlugin, abi_version) - 0usize];
    ["Offset of field: OrcPlugin::name"][::std::mem::offset_of!(OrcPlugin, name) - 8usize];
    ["Offset of field: OrcPlugin::desc"][::std::mem::offset_of!(OrcPlugin, desc) - 16usize];
    ["Offset of field: OrcPlugin::types"][::std::mem::offset_of!(OrcPlugin, types) - 24usize];
    ["Offset of field: OrcPlugin::n_types"][::std::mem::offset_of!(OrcPlugin, n_types) - 32usize];
    ["Offset of field: OrcPlugin::functions"]
        [::std::mem::offset_of!(OrcPlugin, functions) - 40usize];
    ["Offset of field: OrcPlugin::n_functions"]
        [::std::mem::offset_of!(OrcPlugin, n_functions) - 48usize];
};
impl Default for OrcPlugin {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = "Optionally the host may provide a memory allocator for the plugin. This struct is how the\nhost passes the function pointers to the plugin. The host may choose to leave these\n`NULL`, and leave the plugin to use it's own allocator."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct OrcHostMemoryAPI {
    pub alloc: ::std::option::Option<
        unsafe extern "C" fn(size: u64, alignment: u64) -> *mut ::std::os::raw::c_void,
    >,
    pub dealloc: ::std::option::Option<
        unsafe extern "C" fn(ptr: *mut ::std::os::raw::c_void, size: u64, alignment: u64),
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of OrcHostMemoryAPI"][::std::mem::size_of::<OrcHostMemoryAPI>() - 16usize];
    ["Alignment of OrcHostMemoryAPI"][::std::mem::align_of::<OrcHostMemoryAPI>() - 8usize];
    ["Offset of field: OrcHostMemoryAPI::alloc"]
        [::std::mem::offset_of!(OrcHostMemoryAPI, alloc) - 0usize];
    ["Offset of field: OrcHostMemoryAPI::dealloc"]
        [::std::mem::offset_of!(OrcHostMemoryAPI, dealloc) - 8usize];
};
#[doc = "The host may populate any of these function pointers, or leave them as `NULL` to\ncommunicate its capabilities with the plugin.\n\n- report_progress: The plugin can use this to report the progress of a function that is\ncurrently running, back to the host.\n- report_message: The plugin can use this to communicate, errors, warnings, and other\ntypes of messages with the host.\n- check_cancellation: The host may desire to cancel a function call before it completes.\nThe plugin can use this callback to check if the host requested cancellation.\n- report_intermediate_output: Sometiems, plugin functions that take a long time to run may\nchoose to report intermediate data to the host. The plugin can populate one of it's output\nhandles with intermediate data, and call this function to report it to the host."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct OrcHostCallbackAPI {
    pub report_progress: ::std::option::Option<unsafe extern "C" fn(ctx: u64, progress: f64)>,
    pub report_message: ::std::option::Option<
        unsafe extern "C" fn(ctx: u64, level: OrcMessageLevel, msg: *const ::std::os::raw::c_char),
    >,
    pub check_cancellation: ::std::option::Option<unsafe extern "C" fn(ctx: u64) -> bool>,
    pub report_intermediate_output:
        ::std::option::Option<unsafe extern "C" fn(ctx: u64, handle: *const OrcHandle)>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of OrcHostCallbackAPI"][::std::mem::size_of::<OrcHostCallbackAPI>() - 32usize];
    ["Alignment of OrcHostCallbackAPI"][::std::mem::align_of::<OrcHostCallbackAPI>() - 8usize];
    ["Offset of field: OrcHostCallbackAPI::report_progress"]
        [::std::mem::offset_of!(OrcHostCallbackAPI, report_progress) - 0usize];
    ["Offset of field: OrcHostCallbackAPI::report_message"]
        [::std::mem::offset_of!(OrcHostCallbackAPI, report_message) - 8usize];
    ["Offset of field: OrcHostCallbackAPI::check_cancellation"]
        [::std::mem::offset_of!(OrcHostCallbackAPI, check_cancellation) - 16usize];
    ["Offset of field: OrcHostCallbackAPI::report_intermediate_output"]
        [::std::mem::offset_of!(OrcHostCallbackAPI, report_intermediate_output) - 24usize];
};
#[doc = "This is how the host communicates information about itself to the plugin. This includes an\noptional memory allocator, various callbacks etc. The host MUST set the abi_version to\nthat of the header used to compile the host program.\n\n- create_deck_from_proxy: If the plugin wants to create a deck by proxy, of a type that it\ndoesn't own, it will call this function to defer to host. The host must identify which\nother plugin owns that datatype, and dispatch the proxy deck creation to that plugin."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OrcHost {
    pub abi_version: u64,
    pub memory_api: OrcHostMemoryAPI,
    pub callbacks: OrcHostCallbackAPI,
    pub create_deck_from_proxy: ::std::option::Option<
        unsafe extern "C" fn(
            inputs: *const OrcHandle,
            n_inputs: u64,
            proxy_type: OrcProxyType,
            proxy: *const OrcHandle,
            out: *mut OrcHandle,
        ) -> OrcError,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of OrcHost"][::std::mem::size_of::<OrcHost>() - 64usize];
    ["Alignment of OrcHost"][::std::mem::align_of::<OrcHost>() - 8usize];
    ["Offset of field: OrcHost::abi_version"]
        [::std::mem::offset_of!(OrcHost, abi_version) - 0usize];
    ["Offset of field: OrcHost::memory_api"][::std::mem::offset_of!(OrcHost, memory_api) - 8usize];
    ["Offset of field: OrcHost::callbacks"][::std::mem::offset_of!(OrcHost, callbacks) - 24usize];
    ["Offset of field: OrcHost::create_deck_from_proxy"]
        [::std::mem::offset_of!(OrcHost, create_deck_from_proxy) - 56usize];
};
pub type OrcDims = [i32; 7usize];
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct OrcMark {
    pub depth: u8,
    pub pos: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of OrcMark"][::std::mem::size_of::<OrcMark>() - 16usize];
    ["Alignment of OrcMark"][::std::mem::align_of::<OrcMark>() - 8usize];
    ["Offset of field: OrcMark::depth"][::std::mem::offset_of!(OrcMark, depth) - 0usize];
    ["Offset of field: OrcMark::pos"][::std::mem::offset_of!(OrcMark, pos) - 8usize];
};
#[doc = "In C++ vocabulary, this is the destructor of the data behind an `OrcHandle`. When said\ndata doesn't need a destructor, say, when it is allocated directly on the stack, this can\nbe left `NULL` inside `OrcHandle`.\n\nThe plugin or the host may call this function when they want to free the data, and use the\nsame handle to allocate some other data."]
pub type OrcDeckFreeFn =
    ::std::option::Option<unsafe extern "C" fn(handle: *mut OrcHandle) -> OrcError>;
#[doc = "This is the primary handle passed around between hosts and plugins as input and outputs\nfor the plugin function calls.\n\n- handle: This is a unique integer assigned by the host program. The plugin MUST NOT\nmodify it. The plugin may use it as a key to point to data allocated within it's memory,\nwhen said data is owned by the same plugin. The host uses this integer to keep track of\nall the data alive during a session.\n- items, and n_items: These are the actual data stored in the deck that this handles\npoints to. This handle can be backed by any implementation of a Deck datastructure,\nwritten in any language, as long as these pointers meet the ABI requirements to be read\nacross the FFI boundary.\n- marks, stride_offset, and n_mmarks: These define the structure / nesting inside a deck.\n- type_id: Indicates the type of the data stored in the deck backs this handle.\n- dims: Optional units. Just metadata, the plugin functions and host can do whatever they\nwant with it.\n- free_fn: Destructor. Whichever plugin allocates the backing deck, and populates this\nhandle with the corresponding pointers, is also responsible for setting the destructor\nfunction pointer. Without this, the memory may leak."]
#[repr(C)]
#[derive(Debug)]
pub struct OrcHandle {
    pub handle: u64,
    pub items: *const ::std::os::raw::c_void,
    pub n_items: u64,
    pub item_size: u64,
    pub marks: *const OrcMark,
    pub stride_offset: *const u64,
    pub n_marks: u64,
    pub strides: *const u64,
    pub type_id: OrcTypeId,
    pub dims: OrcDims,
    pub free_fn: OrcDeckFreeFn,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of OrcHandle"][::std::mem::size_of::<OrcHandle>() - 112usize];
    ["Alignment of OrcHandle"][::std::mem::align_of::<OrcHandle>() - 8usize];
    ["Offset of field: OrcHandle::handle"][::std::mem::offset_of!(OrcHandle, handle) - 0usize];
    ["Offset of field: OrcHandle::items"][::std::mem::offset_of!(OrcHandle, items) - 8usize];
    ["Offset of field: OrcHandle::n_items"][::std::mem::offset_of!(OrcHandle, n_items) - 16usize];
    ["Offset of field: OrcHandle::item_size"]
        [::std::mem::offset_of!(OrcHandle, item_size) - 24usize];
    ["Offset of field: OrcHandle::marks"][::std::mem::offset_of!(OrcHandle, marks) - 32usize];
    ["Offset of field: OrcHandle::stride_offset"]
        [::std::mem::offset_of!(OrcHandle, stride_offset) - 40usize];
    ["Offset of field: OrcHandle::n_marks"][::std::mem::offset_of!(OrcHandle, n_marks) - 48usize];
    ["Offset of field: OrcHandle::strides"][::std::mem::offset_of!(OrcHandle, strides) - 56usize];
    ["Offset of field: OrcHandle::type_id"][::std::mem::offset_of!(OrcHandle, type_id) - 64usize];
    ["Offset of field: OrcHandle::dims"][::std::mem::offset_of!(OrcHandle, dims) - 72usize];
    ["Offset of field: OrcHandle::free_fn"][::std::mem::offset_of!(OrcHandle, free_fn) - 104usize];
};
impl Default for OrcHandle {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = "Each plugin has to provide a generic way to construct decks out of a given input deck, for\nall of its custom datatypes. This proxy refers to a particular item in a particular deck.\nBoth the deck and the item are referenced by their index."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct OrcItemProxy {
    pub tree: u64,
    pub item: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of OrcItemProxy"][::std::mem::size_of::<OrcItemProxy>() - 16usize];
    ["Alignment of OrcItemProxy"][::std::mem::align_of::<OrcItemProxy>() - 8usize];
    ["Offset of field: OrcItemProxy::tree"][::std::mem::offset_of!(OrcItemProxy, tree) - 0usize];
    ["Offset of field: OrcItemProxy::item"][::std::mem::offset_of!(OrcItemProxy, item) - 8usize];
};
unsafe extern "C" {
    #[doc = "The host will call this plugin when it loads a plugin. It must communicate it's own\ncapabilities via the host argument, and let the plugin populate it's own information into\nteh `plugin_data_out` argument."]
    pub fn orc_plugin_init(host: *const OrcHost, plugin_data_out: *mut OrcPlugin) -> OrcError;
}
unsafe extern "C" {
    #[doc = "The host may call this function to allocate a deck for this handle. The plugin must\nrespect the `out->handle` property. It must not be modified, and must be used as a key to\npoint to the allocated data, until `orc_deck_free` is called, with the same `handle`\nproperty."]
    pub fn orc_deck_alloc(id: OrcTypeId, out: *mut OrcHandle) -> OrcError;
}
unsafe extern "C" {
    pub fn orc_deck_free(handle: *mut OrcHandle) -> OrcError;
}
unsafe extern "C" {
    pub fn orc_deck_from_proxy(
        inputs: *const OrcHandle,
        n_inputs: u64,
        proxy_type: OrcProxyType,
        proxy: *const OrcHandle,
        out: *mut OrcHandle,
    ) -> OrcError;
}
