name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y cmake
      - name: Update Rust
        run: rustup update stable
      - name: Build C (Debug)
        run: cmake -S c/ -B build/debug -DCMAKE_BUILD_TYPE=Debug && cmake --build build/debug
      - name: Run C tests
        run: ctest --test-dir build/debug --output-on-failure
      - name: Build Rust
        run: cargo build --verbose --all-targets --all-features
      - name: Check Rust formatting
        run: cargo fmt --all -- --check
      - name: Run Rust Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run Rust tests
        run: cargo test --all-features --verbose
      - name: Generate Rust docs
        run: cargo doc --all-features --no-deps
      - name: Run Python tests
        working-directory: python
        run: python3 test.py

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable
      - name: Build C (Debug)
        run: cmake -S c/ -B build/debug -DCMAKE_BUILD_TYPE=Debug && cmake --build build/debug --config Debug
      - name: Run C tests
        run: ctest --test-dir build/debug -C Debug --output-on-failure
      - name: Build Rust
        run: cargo build --verbose --all-targets --all-features
      - name: Check Rust formatting
        run: cargo fmt --all -- --check
      - name: Run Rust Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run Rust tests
        run: cargo test --all-features --verbose
      - name: Generate Rust docs
        run: cargo doc --all-features --no-deps
      - name: Run Python tests
        working-directory: python
        run: python3 test.py

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable
      - name: Build C (Debug)
        run: cmake -B build/debug -S c -DCMAKE_BUILD_TYPE=Debug && cmake --build build/debug
      - name: Run C tests
        run: ctest --test-dir build/debug --output-on-failure
      - name: Build Rust
        run: cargo build --verbose --all-targets --all-features
      - name: Check Rust formatting
        run: cargo fmt --all -- --check
      - name: Run Rust Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run Rust tests
        run: cargo test --all-features --verbose
      - name: Generate Rust docs
        run: cargo doc --all-features --no-deps
      - name: Run Python tests
        working-directory: python
        run: python3 test.py
