name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: "-D warnings"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y cmake
      - name: Update Rust
        run: rustup update stable
      - name: Check bindings
        run: cargo run -p bindings_generator -- c/orc_abi.h --rust-check rust/orc_sdk/src/bindings.rs
      - name: Build C and C++ (Debug)
        run: cmake -S . -B build/debug -DCMAKE_BUILD_TYPE=Debug && cmake --build build/debug
      - name: Run C tests
        run: build/debug/orc_sdk_tests && build/debug/example_c_plugin_tests
      - name: Run C++ tests
        run: build/debug/orc_sdk_cpp_tests
      - name: Build Rust
        run: cargo build --verbose --all-targets --all-features
      - name: Check Rust formatting
        run: cargo fmt --all -- --check
      - name: Run Rust Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run Rust tests
        run: cargo test --all-features --verbose
      - name: Generate Rust docs
        run: cargo doc --all-features --no-deps
      - name: Install Python dependencies
        run: |
          python3 -m venv .venv
          .venv/bin/pip install numpy
          .venv/bin/pip install ./rust/pyorc
      - name: Run Python tests
        working-directory: python
        run: |
          ../.venv/bin/python3 test.py
          ../.venv/bin/python3 integration_tests.py

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable
      - name: Check bindings
        run: cargo run -p bindings_generator -- c/orc_abi.h --rust-check rust/orc_sdk/src/bindings.rs
      - name: Build C and C++ (Debug)
        run: cmake -S . -B build/debug -DCMAKE_BUILD_TYPE=Debug && cmake --build build/debug --config Debug
      - name: Run C tests
        run: build/debug/orc_sdk_tests.exe && build/debug/example_c_plugin_tests.exe
      - name: Run C++ tests
        run: build/debug/orc_sdk_cpp_tests.exe
      - name: Build Rust
        run: cargo build --verbose --all-targets --all-features
      - name: Check Rust formatting
        run: cargo fmt --all -- --check
      - name: Run Rust Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run Rust tests
        run: cargo test --all-features --verbose
      - name: Generate Rust docs
        run: cargo doc --all-features --no-deps
      - name: Install Python dependencies
        run: |
          python3 -m venv .venv
          .venv/Scripts/pip install numpy
          .venv/Scripts/pip install ./rust/pyorc
      - name: Run Python tests
        working-directory: python
        run: |
          ../.venv/Scripts/python3 test.py
          ../.venv/Scripts/python3 integration_tests.py

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable
      - name: Check bindings
        run: cargo run -p bindings_generator -- c/orc_abi.h --rust-check rust/orc_sdk/src/bindings.rs
      - name: Build C and C++ (Debug)
        run: cmake -S . -B build/debug -DCMAKE_BUILD_TYPE=Debug && cmake --build build/debug
      - name: Run C tests
        run: build/debug/orc_sdk_tests && build/debug/example_c_plugin_tests
      - name: Run C++ tests
        run: build/debug/orc_sdk_cpp_tests
      - name: Build Rust
        run: cargo build --verbose --all-targets --all-features
      - name: Check Rust formatting
        run: cargo fmt --all -- --check
      - name: Run Rust Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run Rust tests
        run: cargo test --all-features --verbose
      - name: Generate Rust docs
        run: cargo doc --all-features --no-deps
      - name: Install Python dependencies
        run: |
          python3 -m venv .venv
          .venv/bin/pip install numpy
          .venv/bin/pip install ./rust/pyorc
      - name: Run Python tests
        working-directory: python
        run: |
          ../.venv/bin/python3 test.py
          ../.venv/bin/python3 integration_tests.py
